apiVersion: v1
kind: PersistentVolume
metadata:
  name: busapp-vol1
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
   volumeID: vol-0d8a36ff5f6ea8a0b
   fsType: xfs
  storageClassName: gp2
